package ar.edu.um.prog2.turnosyreservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HoldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAllPropertiesEquals(Hold expected, Hold actual) {
        assertHoldAutoGeneratedPropertiesEquals(expected, actual);
        assertHoldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAllUpdatablePropertiesEquals(Hold expected, Hold actual) {
        assertHoldUpdatableFieldsEquals(expected, actual);
        assertHoldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldAutoGeneratedPropertiesEquals(Hold expected, Hold actual) {
        assertThat(actual)
            .as("Verify Hold auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldUpdatableFieldsEquals(Hold expected, Hold actual) {
        assertThat(actual)
            .as("Verify Hold relevant properties")
            .satisfies(a -> assertThat(a.getExternalHoldId()).as("check externalHoldId").isEqualTo(expected.getExternalHoldId()))
            .satisfies(a -> assertThat(a.getExternalProcessId()).as("check externalProcessId").isEqualTo(expected.getExternalProcessId()))
            .satisfies(a -> assertThat(a.getProfessionalId()).as("check professionalId").isEqualTo(expected.getProfessionalId()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHoldUpdatableRelationshipsEquals(Hold expected, Hold actual) {
        // empty method
    }
}
