package ar.edu.um.prog2.turnosyreservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAllPropertiesEquals(Reservation expected, Reservation actual) {
        assertReservationAutoGeneratedPropertiesEquals(expected, actual);
        assertReservationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAllUpdatablePropertiesEquals(Reservation expected, Reservation actual) {
        assertReservationUpdatableFieldsEquals(expected, actual);
        assertReservationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationAutoGeneratedPropertiesEquals(Reservation expected, Reservation actual) {
        assertThat(actual)
            .as("Verify Reservation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationUpdatableFieldsEquals(Reservation expected, Reservation actual) {
        assertThat(actual)
            .as("Verify Reservation relevant properties")
            .satisfies(a ->
                assertThat(a.getExternalReservationId()).as("check externalReservationId").isEqualTo(expected.getExternalReservationId())
            )
            .satisfies(a -> assertThat(a.getProfessionalId()).as("check professionalId").isEqualTo(expected.getProfessionalId()))
            .satisfies(a ->
                assertThat(a.getProfessionalFirstName()).as("check professionalFirstName").isEqualTo(expected.getProfessionalFirstName())
            )
            .satisfies(a ->
                assertThat(a.getProfessionalLastName()).as("check professionalLastName").isEqualTo(expected.getProfessionalLastName())
            )
            .satisfies(a -> assertThat(a.getAppointmentDate()).as("check appointmentDate").isEqualTo(expected.getAppointmentDate()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getPatientFirstName()).as("check patientFirstName").isEqualTo(expected.getPatientFirstName()))
            .satisfies(a -> assertThat(a.getPatientLastName()).as("check patientLastName").isEqualTo(expected.getPatientLastName()))
            .satisfies(a -> assertThat(a.getPatientPhone()).as("check patientPhone").isEqualTo(expected.getPatientPhone()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getConfirmedAt()).as("check confirmedAt").isEqualTo(expected.getConfirmedAt()))
            .satisfies(a -> assertThat(a.getCancelledAt()).as("check cancelledAt").isEqualTo(expected.getCancelledAt()))
            .satisfies(a -> assertThat(a.getCancellationReason()).as("check cancellationReason").isEqualTo(expected.getCancellationReason())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationUpdatableRelationshipsEquals(Reservation expected, Reservation actual) {
        assertThat(actual)
            .as("Verify Reservation relationships")
            .satisfies(a -> assertThat(a.getProcess()).as("check process").isEqualTo(expected.getProcess()));
    }
}
