package ar.edu.um.prog2.turnosyreservas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservationProcessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationProcessAllPropertiesEquals(ReservationProcess expected, ReservationProcess actual) {
        assertReservationProcessAutoGeneratedPropertiesEquals(expected, actual);
        assertReservationProcessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationProcessAllUpdatablePropertiesEquals(ReservationProcess expected, ReservationProcess actual) {
        assertReservationProcessUpdatableFieldsEquals(expected, actual);
        assertReservationProcessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationProcessAutoGeneratedPropertiesEquals(ReservationProcess expected, ReservationProcess actual) {
        assertThat(actual)
            .as("Verify ReservationProcess auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationProcessUpdatableFieldsEquals(ReservationProcess expected, ReservationProcess actual) {
        assertThat(actual)
            .as("Verify ReservationProcess relevant properties")
            .satisfies(a -> assertThat(a.getExternalProcessId()).as("check externalProcessId").isEqualTo(expected.getExternalProcessId()))
            .satisfies(a -> assertThat(a.getProfessionalId()).as("check professionalId").isEqualTo(expected.getProfessionalId()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getPatientFirstName()).as("check patientFirstName").isEqualTo(expected.getPatientFirstName()))
            .satisfies(a -> assertThat(a.getPatientLastName()).as("check patientLastName").isEqualTo(expected.getPatientLastName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getRequestEventId()).as("check requestEventId").isEqualTo(expected.getRequestEventId()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationProcessUpdatableRelationshipsEquals(ReservationProcess expected, ReservationProcess actual) {
        assertThat(actual)
            .as("Verify ReservationProcess relationships")
            .satisfies(a -> assertThat(a.getHold()).as("check hold").isEqualTo(expected.getHold()));
    }
}
